PRICE_TABLE_GENERAL = [
    {'item': 'ドライTシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2200},
    {'item': 'ドライTシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2050},
    {'item': 'ドライTシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 1900},
    {'item': 'ドライTシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 1750},
    {'item': 'ドライTシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 1600},
    {'item': 'ドライTシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1450},
    {'item': 'ドライTシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 2700},
    {'item': 'ドライTシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2550},
    {'item': 'ドライTシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'ドライTシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2250},
    {'item': 'ドライTシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2100},
    {'item': 'ドライTシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 1950},
    {'item': 'ドライTシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 2700},
    {'item': 'ドライTシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2550},
    {'item': 'ドライTシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'ドライTシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2250},
    {'item': 'ドライTシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2100},
    {'item': 'ドライTシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 1950},
    {'item': 'ドライTシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'ドライTシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'ドライTシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'ドライTシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'ドライTシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'ドライTシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'ドライTシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'ドライTシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'ドライTシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'ドライTシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'ドライTシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'ドライTシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'ドライTシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 1000},
    {'item': 'ドライTシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 950},
    {'item': 'ドライTシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 900},
    {'item': 'ドライTシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 850},
    {'item': 'ドライTシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 800},
    {'item': 'ドライTシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 750},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 3000},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2850},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2700},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 2550},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 2400},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 2250},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 2000},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1950},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1900},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1850},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1800},
    {'item': 'ハイクオリティーTシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1750},
    {'item': 'ドライロングTシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2500},
    {'item': 'ドライロングTシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2350},
    {'item': 'ドライロングTシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2200},
    {'item': 'ドライロングTシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 2050},
    {'item': 'ドライロングTシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 1900},
    {'item': 'ドライロングTシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1750},
    {'item': 'ドライロングTシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 3000},
    {'item': 'ドライロングTシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2850},
    {'item': 'ドライロングTシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2700},
    {'item': 'ドライロングTシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2550},
    {'item': 'ドライロングTシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2400},
    {'item': 'ドライロングTシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2250},
    {'item': 'ドライロングTシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 3000},
    {'item': 'ドライロングTシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2850},
    {'item': 'ドライロングTシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2700},
    {'item': 'ドライロングTシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2550},
    {'item': 'ドライロングTシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2400},
    {'item': 'ドライロングTシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2250},
    {'item': 'ドライロングTシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'ドライロングTシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'ドライロングTシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'ドライロングTシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'ドライロングTシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'ドライロングTシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'ドライロングTシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'ドライロングTシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'ドライロングTシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'ドライロングTシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'ドライロングTシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'ドライロングTシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'ドライロングTシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 1500},
    {'item': 'ドライロングTシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1450},
    {'item': 'ドライロングTシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1400},
    {'item': 'ドライロングTシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1350},
    {'item': 'ドライロングTシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1300},
    {'item': 'ドライロングTシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1250},
    {'item': 'ドライポロシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2200},
    {'item': 'ドライポロシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2050},
    {'item': 'ドライポロシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 1900},
    {'item': 'ドライポロシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 1750},
    {'item': 'ドライポロシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 1600},
    {'item': 'ドライポロシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1450},
    {'item': 'ドライポロシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 2700},
    {'item': 'ドライポロシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2550},
    {'item': 'ドライポロシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'ドライポロシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2250},
    {'item': 'ドライポロシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2100},
    {'item': 'ドライポロシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 1950},
    {'item': 'ドライポロシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 2700},
    {'item': 'ドライポロシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2550},
    {'item': 'ドライポロシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'ドライポロシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2250},
    {'item': 'ドライポロシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2100},
    {'item': 'ドライポロシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 1950},
    {'item': 'ドライポロシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'ドライポロシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'ドライポロシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'ドライポロシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'ドライポロシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'ドライポロシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'ドライポロシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'ドライポロシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'ドライポロシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'ドライポロシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'ドライポロシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'ドライポロシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'ドライポロシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 1200},
    {'item': 'ドライポロシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1150},
    {'item': 'ドライポロシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1100},
    {'item': 'ドライポロシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1050},
    {'item': 'ドライポロシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1000},
    {'item': 'ドライポロシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 950},
    {'item': 'ゲームシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2200},
    {'item': 'ゲームシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2050},
    {'item': 'ゲームシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 1900},
    {'item': 'ゲームシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 1750},
    {'item': 'ゲームシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 1600},
    {'item': 'ゲームシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1450},
    {'item': 'ゲームシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 2700},
    {'item': 'ゲームシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2550},
    {'item': 'ゲームシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'ゲームシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2250},
    {'item': 'ゲームシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2100},
    {'item': 'ゲームシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 1950},
    {'item': 'ゲームシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 2700},
    {'item': 'ゲームシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2550},
    {'item': 'ゲームシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'ゲームシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2250},
    {'item': 'ゲームシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2100},
    {'item': 'ゲームシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 1950},
    {'item': 'ゲームシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'ゲームシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'ゲームシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'ゲームシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'ゲームシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'ゲームシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'ゲームシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'ゲームシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'ゲームシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'ゲームシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'ゲームシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'ゲームシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'ゲームシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 1500},
    {'item': 'ゲームシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1450},
    {'item': 'ゲームシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1400},
    {'item': 'ゲームシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1350},
    {'item': 'ゲームシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1300},
    {'item': 'ゲームシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1250},
    {'item': 'ベースボールシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2400},
    {'item': 'ベースボールシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2250},
    {'item': 'ベースボールシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2100},
    {'item': 'ベースボールシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 1950},
    {'item': 'ベースボールシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 1800},
    {'item': 'ベースボールシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1650},
    {'item': 'ベースボールシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 2900},
    {'item': 'ベースボールシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2750},
    {'item': 'ベースボールシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2600},
    {'item': 'ベースボールシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2450},
    {'item': 'ベースボールシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2300},
    {'item': 'ベースボールシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2150},
    {'item': 'ベースボールシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 2900},
    {'item': 'ベースボールシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2750},
    {'item': 'ベースボールシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2600},
    {'item': 'ベースボールシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2450},
    {'item': 'ベースボールシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2300},
    {'item': 'ベースボールシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2150},
    {'item': 'ベースボールシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3400},
    {'item': 'ベースボールシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3250},
    {'item': 'ベースボールシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3100},
    {'item': 'ベースボールシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 2950},
    {'item': 'ベースボールシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 2800},
    {'item': 'ベースボールシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2650},
    {'item': 'ベースボールシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3400},
    {'item': 'ベースボールシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3250},
    {'item': 'ベースボールシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3100},
    {'item': 'ベースボールシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 2950},
    {'item': 'ベースボールシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 2800},
    {'item': 'ベースボールシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2650},
    {'item': 'ベースボールシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 1700},
    {'item': 'ベースボールシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1650},
    {'item': 'ベースボールシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1600},
    {'item': 'ベースボールシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1550},
    {'item': 'ベースボールシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1500},
    {'item': 'ベースボールシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1450},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2600},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2450},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2300},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 2150},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 2000},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1850},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 3100},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2950},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2800},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2650},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2500},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2350},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 3100},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2950},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2800},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2650},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2500},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2350},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3600},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3450},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3300},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 3150},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 3000},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2850},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3600},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3450},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3300},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 3150},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 3000},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2850},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 2000},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1950},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1900},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1850},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1800},
    {'item': 'ストライプベースボールシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1750},
    {'item': 'ストライプユニフォーム', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 2300},
    {'item': 'ストライプユニフォーム', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2150},
    {'item': 'ストライプユニフォーム', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2000},
    {'item': 'ストライプユニフォーム', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 1850},
    {'item': 'ストライプユニフォーム', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 1700},
    {'item': 'ストライプユニフォーム', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 1550},
    {'item': 'ストライプユニフォーム', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 2800},
    {'item': 'ストライプユニフォーム', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 2650},
    {'item': 'ストライプユニフォーム', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 2500},
    {'item': 'ストライプユニフォーム', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 2350},
    {'item': 'ストライプユニフォーム', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2200},
    {'item': 'ストライプユニフォーム', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2050},
    {'item': 'ストライプユニフォーム', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 2800},
    {'item': 'ストライプユニフォーム', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 2650},
    {'item': 'ストライプユニフォーム', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 2500},
    {'item': 'ストライプユニフォーム', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 2350},
    {'item': 'ストライプユニフォーム', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2200},
    {'item': 'ストライプユニフォーム', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2050},
    {'item': 'ストライプユニフォーム', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 3300},
    {'item': 'ストライプユニフォーム', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3150},
    {'item': 'ストライプユニフォーム', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3000},
    {'item': 'ストライプユニフォーム', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 2850},
    {'item': 'ストライプユニフォーム', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 2700},
    {'item': 'ストライプユニフォーム', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 2550},
    {'item': 'ストライプユニフォーム', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 3300},
    {'item': 'ストライプユニフォーム', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3150},
    {'item': 'ストライプユニフォーム', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3000},
    {'item': 'ストライプユニフォーム', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 2850},
    {'item': 'ストライプユニフォーム', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 2700},
    {'item': 'ストライプユニフォーム', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 2550},
    {'item': 'ストライプユニフォーム', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 1700},
    {'item': 'ストライプユニフォーム', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1650},
    {'item': 'ストライプユニフォーム', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1600},
    {'item': 'ストライプユニフォーム', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1550},
    {'item': 'ストライプユニフォーム', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1500},
    {'item': 'ストライプユニフォーム', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1450},
    {'item': 'クールネックライトトレーナー', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 3200},
    {'item': 'クールネックライトトレーナー', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 3050},
    {'item': 'クールネックライトトレーナー', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'クールネックライトトレーナー', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 2750},
    {'item': 'クールネックライトトレーナー', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 2600},
    {'item': 'クールネックライトトレーナー', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 2450},
    {'item': 'クールネックライトトレーナー', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 3700},
    {'item': 'クールネックライトトレーナー', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 3550},
    {'item': 'クールネックライトトレーナー', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 3400},
    {'item': 'クールネックライトトレーナー', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 3250},
    {'item': 'クールネックライトトレーナー', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 3100},
    {'item': 'クールネックライトトレーナー', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2950},
    {'item': 'クールネックライトトレーナー', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 3700},
    {'item': 'クールネックライトトレーナー', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 3550},
    {'item': 'クールネックライトトレーナー', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 3400},
    {'item': 'クールネックライトトレーナー', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 3250},
    {'item': 'クールネックライトトレーナー', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 3100},
    {'item': 'クールネックライトトレーナー', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2950},
    {'item': 'クールネックライトトレーナー', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 4200},
    {'item': 'クールネックライトトレーナー', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 4050},
    {'item': 'クールネックライトトレーナー', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3900},
    {'item': 'クールネックライトトレーナー', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 3750},
    {'item': 'クールネックライトトレーナー', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 3600},
    {'item': 'クールネックライトトレーナー', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 3450},
    {'item': 'クールネックライトトレーナー', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 4200},
    {'item': 'クールネックライトトレーナー', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 4050},
    {'item': 'クールネックライトトレーナー', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3900},
    {'item': 'クールネックライトトレーナー', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 3750},
    {'item': 'クールネックライトトレーナー', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 3600},
    {'item': 'クールネックライトトレーナー', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 3450},
    {'item': 'クールネックライトトレーナー', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 2500},
    {'item': 'クールネックライトトレーナー', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 2450},
    {'item': 'クールネックライトトレーナー', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'クールネックライトトレーナー', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 2350},
    {'item': 'クールネックライトトレーナー', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 2300},
    {'item': 'クールネックライトトレーナー', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 2250},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 4500},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 4350},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 4200},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 4050},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 3900},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 3750},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 4500},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 4350},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 4200},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 4050},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 3900},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 3750},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 2000},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 1950},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 1900},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 1850},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 1800},
    {'item': 'ジップアップライトトレーナー', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 1750},
    {'item': 'フーディーライトトレーナー', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'フーディーライトトレーナー', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'フーディーライトトレーナー', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'フーディーライトトレーナー', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'フーディーライトトレーナー', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'フーディーライトトレーナー', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'フーディーライトトレーナー', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 4500},
    {'item': 'フーディーライトトレーナー', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 4350},
    {'item': 'フーディーライトトレーナー', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 4200},
    {'item': 'フーディーライトトレーナー', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 4050},
    {'item': 'フーディーライトトレーナー', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 3900},
    {'item': 'フーディーライトトレーナー', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 3750},
    {'item': 'フーディーライトトレーナー', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 4500},
    {'item': 'フーディーライトトレーナー', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 4350},
    {'item': 'フーディーライトトレーナー', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 4200},
    {'item': 'フーディーライトトレーナー', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 4050},
    {'item': 'フーディーライトトレーナー', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 3900},
    {'item': 'フーディーライトトレーナー', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 3750},
    {'item': 'フーディーライトトレーナー', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 5000},
    {'item': 'フーディーライトトレーナー', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 4850},
    {'item': 'フーディーライトトレーナー', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 4700},
    {'item': 'フーディーライトトレーナー', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 4550},
    {'item': 'フーディーライトトレーナー', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 4400},
    {'item': 'フーディーライトトレーナー', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 4250},
    {'item': 'フーディーライトトレーナー', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 5000},
    {'item': 'フーディーライトトレーナー', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 4850},
    {'item': 'フーディーライトトレーナー', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 4700},
    {'item': 'フーディーライトトレーナー', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 4550},
    {'item': 'フーディーライトトレーナー', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 4400},
    {'item': 'フーディーライトトレーナー', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 4250},
    {'item': 'フーディーライトトレーナー', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 3000},
    {'item': 'フーディーライトトレーナー', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 2950},
    {'item': 'フーディーライトトレーナー', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 2900},
    {'item': 'フーディーライトトレーナー', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 2850},
    {'item': 'フーディーライトトレーナー', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 2800},
    {'item': 'フーディーライトトレーナー', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'バスケシャツ', 'pattern': 'A', 'quantity_range': '10〜19枚', 'unit_price': 3000},
    {'item': 'バスケシャツ', 'pattern': 'A', 'quantity_range': '20〜29枚', 'unit_price': 2850},
    {'item': 'バスケシャツ', 'pattern': 'A', 'quantity_range': '30〜39枚', 'unit_price': 2700},
    {'item': 'バスケシャツ', 'pattern': 'A', 'quantity_range': '40〜49枚', 'unit_price': 2550},
    {'item': 'バスケシャツ', 'pattern': 'A', 'quantity_range': '50〜99枚', 'unit_price': 2400},
    {'item': 'バスケシャツ', 'pattern': 'A', 'quantity_range': '100枚以上', 'unit_price': 2250},
    {'item': 'バスケシャツ', 'pattern': 'B', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'バスケシャツ', 'pattern': 'B', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'バスケシャツ', 'pattern': 'B', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'バスケシャツ', 'pattern': 'B', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'バスケシャツ', 'pattern': 'B', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'バスケシャツ', 'pattern': 'B', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'バスケシャツ', 'pattern': 'C', 'quantity_range': '10〜19枚', 'unit_price': 3500},
    {'item': 'バスケシャツ', 'pattern': 'C', 'quantity_range': '20〜29枚', 'unit_price': 3350},
    {'item': 'バスケシャツ', 'pattern': 'C', 'quantity_range': '30〜39枚', 'unit_price': 3200},
    {'item': 'バスケシャツ', 'pattern': 'C', 'quantity_range': '40〜49枚', 'unit_price': 3050},
    {'item': 'バスケシャツ', 'pattern': 'C', 'quantity_range': '50〜99枚', 'unit_price': 2900},
    {'item': 'バスケシャツ', 'pattern': 'C', 'quantity_range': '100枚以上', 'unit_price': 2750},
    {'item': 'バスケシャツ', 'pattern': 'D', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'バスケシャツ', 'pattern': 'D', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'バスケシャツ', 'pattern': 'D', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'バスケシャツ', 'pattern': 'D', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'バスケシャツ', 'pattern': 'D', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'バスケシャツ', 'pattern': 'D', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'バスケシャツ', 'pattern': 'E', 'quantity_range': '10〜19枚', 'unit_price': 4000},
    {'item': 'バスケシャツ', 'pattern': 'E', 'quantity_range': '20〜29枚', 'unit_price': 3850},
    {'item': 'バスケシャツ', 'pattern': 'E', 'quantity_range': '30〜39枚', 'unit_price': 3700},
    {'item': 'バスケシャツ', 'pattern': 'E', 'quantity_range': '40〜49枚', 'unit_price': 3550},
    {'item': 'バスケシャツ', 'pattern': 'E', 'quantity_range': '50〜99枚', 'unit_price': 3400},
    {'item': 'バスケシャツ', 'pattern': 'E', 'quantity_range': '100枚以上', 'unit_price': 3250},
    {'item': 'バスケシャツ', 'pattern': 'F', 'quantity_range': '10〜19枚', 'unit_price': 2500},
    {'item': 'バスケシャツ', 'pattern': 'F', 'quantity_range': '20〜29枚', 'unit_price': 2450},
    {'item': 'バスケシャツ', 'pattern': 'F', 'quantity_range': '30〜39枚', 'unit_price': 2400},
    {'item': 'バスケシャツ', 'pattern': 'F', 'quantity_range': '40〜49枚', 'unit_price': 2350},
    {'item': 'バスケシャツ', 'pattern': 'F', 'quantity_range': '50〜99枚', 'unit_price': 2300},
    {'item': 'バスケシャツ', 'pattern': 'F', 'quantity_range': '100枚以上', 'unit_price': 2250},
]

COLOR_COST_MAP = {
    "前 or 背中 1色": (0, 0),
    "前 or 背中 2色": (1, 0),
    "前 or 背中 フルカラー": (0, 1),
    "前と背中 前1色 背中1色": (0, 0),
    "前と背中 前2色 背中1色": (1, 0),
    "前と背中 前1色 背中2色": (1, 0),
    "前と背中 前2色 背中2色": (2, 0),
    "前と背中 フルカラー": (0, 2),
}

# プリントカラー → 属性（オプションインク／レギュラーインク 等）
COLOR_ATTR_MAP = {
    # ――― レギュラーインク ―――
    "ホワイト":"レギュラーインク",
    "ライトグレー":"レギュラーインク",
    "ダークグレー":"レギュラーインク",
    "ブラック":"レギュラーインク",
    "サックス":"レギュラーインク",
    "ブルー":"レギュラーインク",
    "ネイビー":"レギュラーインク",
    "ライトピンク":"レギュラーインク",
    "ローズピンク":"レギュラーインク",
    "ホットピンク":"レギュラーインク",
    "レッド":"レギュラーインク",
    "ワインレッド":"レギュラーインク",
    "ミントグリーン":"レギュラーインク",
    "エメラルドグリーン":"レギュラーインク",
    "パステルイエロー":"レギュラーインク",
    "イエロー":"レギュラーインク",
    "ゴールドイエロー":"レギュラーインク",
    "オレンジ":"レギュラーインク",
    "イエローグリーン":"レギュラーインク",
    "グリーン":"レギュラーインク",
    "ダークグリーン":"レギュラーインク",
    "ライトパープル":"レギュラーインク",
    "パープル":"レギュラーインク",
    "クリーム":"レギュラーインク",
    "ライトブラウン":"レギュラーインク",
    "ダークブラウン":"レギュラーインク",
    "シルバー":"レギュラーインク",
    "ゴールド":"レギュラーインク",

    # ――― オプションインク ―――
    "グリッターシルバー":"オプションインク",
    "グリッターゴールド":"オプションインク",
    "グリッターブラック":"オプションインク",
    "グリッターイエロー":"オプションインク",
    "グリッターピンク":"オプションインク",
    "グリッターレッド":"オプションインク",
    "グリッターグリーン":"オプションインク",
    "グリッターブルー":"オプションインク",
    "グリッターパープル":"オプションインク",
    "蛍光イエロー":"オプションインク",
    "蛍光オレンジ":"オプションインク",
    "蛍光ピンク":"オプションインク",
    "蛍光グリーン":"オプションインク",
}

SPECIAL_SINGLE_COLOR_FEE = {                   # 単色＋メタリック系 etc.
    "シルバー":150, "ゴールド":150,
    "グリッターシルバー":200, "グリッターゴールド":200,
    "グリッターブラック":200, "グリッターピンク":200
}

FULLCOLOR_SIZE_FEE = { "小":350, "中":550, "大":990 }   # fullColorSizeX 値
BACK_NAME_FEE = {        # nameNumberOptionX に応じた固定費
    "ネーム＆背番号セット":800,
    "ネーム(大)":550, "ネーム(小)":300,
    "番号(大)":300, "番号(小)":300
}
OPTION_INK_EXTRA = 100   # オプションインク１色あたり